services:
  mcdr:
    build: .
    ports:
      - "8000-8100:8000"
      - "25565-25665:25565" # mc server
      - "25575-25675:25575" # rcon
    volumes:
      - ./data:/data
    command: start_mcdr.sh
    restart: unless-stopped
    tty: true
    stdin_open: true
