services:
  mcdr:
    build: .
    container_name: "mc_${SERVER_NAME}"
    ports:
      - "${MC_HOST_PORT}:25565"
      - "${RCON_HOST_PORT}:25575"
    volumes:
      - ./data:/data
    command: start_mcdr.sh
    restart: unless-stopped
    tty: true
    stdin_open: true
